# Generated by Django 4.1.3 on 2024-11-19 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата заселения')),
                ('eviction_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата выселения')),
                ('costs', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_dormitory', models.SmallIntegerField(verbose_name='Номер общежития')),
                ('place_dormitory', models.CharField(max_length=500, verbose_name='Адрес')),
                ('seats', models.SmallIntegerField(verbose_name='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Группа')),
                ('course', models.CharField(max_length=2, verbose_name='Курс')),
                ('enrollment_year', models.IntegerField(verbose_name='Год зачисления')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.SmallIntegerField(verbose_name='Номер комнаты')),
                ('check_in_count', models.IntegerField(verbose_name='Количество заселенных')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('curs', models.IntegerField(verbose_name='Курс')),
                ('record_book', models.IntegerField(verbose_name='Номер зачетной книжки')),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата рождения')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.group', verbose_name='Группа')),
            ],
        ),
    ]
