# Generated by Django 5.1.3 on 2024-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Группа')),
                ('course', models.CharField(max_length=2, verbose_name='Курс')),
                ('enrollment_year', models.IntegerField(verbose_name='Год зачисления')),
            ],
        ),
    ]
