# Generated by Django 4.1.3 on 2024-11-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group',
        ),
    ]
